### ISSUE TITLE
Get another users feed

### ISSUE THREAD

**Issue by JmzTaylor** [AlexiCoard/flutter_feed#7]
How would I display another users feed instead of my own?

**Comment by JmzTaylor** [comment]
NVM.  appending ?screen_name= works.

**Comment by AlexiCoard** [comment]
That's a good question . I will add a parameter in the widget to specify the query you want. We might want to get another user timeline or search a particular hashtag

**Comment by AlexiCoard** [comment]
There you go : https://github.com/AlexiCoard/flutter_feed/pull/8
