### ISSUE TITLE
Twitter dart package incompatible

### ISSUE THREAD

**Issue by wal33d006** [AlexiCoard/flutter_feed#9]
Your project won't work because the twitter package you are using is not compatible with Dart 2.0 and above

**Comment by SamuelDansokho** [comment]
it would be lovely to have an improvement here....

**Comment by AlexiCoard** [comment]
Will try to have a look soon

**Comment by nathantaal** [comment]
> Will try to have a look soon

Any news?

**Comment by AlexiCoard** [comment]
This is fixed on the master branch.
You can also use version 1.0
